### ISSUE TITLE
in tiny_fMRI_inference, parpool() fails on Matlab Online

### ISSUE THREAD

**Issue by stevevanhooser** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#38]
The following expression fails on Matlab online.

```
if isempty(gcp("nocreate"))
    parpool();
end
```

Is the best solution to just put the parpool() inside a try loop?

that is,

```
if isempty(gcp("nocreate"))
    try, parpool(); end;
end
```

Or is there a better solution? 

Thanks @tkuenzmw

**Comment by tkuenzmw** [comment]
That is expected, since Matlab online per default does not have parallel profiles. The error message is:
`>> p = parpool()
Starting parallel pool (parpool) using the 'local' profile ...
Error using [parpool](matlab:matlab.internal.language.introspective.errorDocCallback('parpool'))
No default cluster available. [Create a cluster and its associated profile](matlab:parallel.internal.cloud.createCloudCluster).`
I think it is best to remove this part of the code altogether. If people run the example on a multi-core machine the parfor will automatically open a worker pool OR it will run serially in all other instances. I'll fix it.
