### ISSUE TITLE
Add more pretrained models to json file

### ISSUE THREAD

**Issue by stevevanhooser** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#60]

**Comment by stevevanhooser** [comment]
Also, update TODO fields and remove sizes except for > 1 GB files

**Comment by vijayiyer05** [comment]
Capturing notes here from a passthrough of the examples & their corresponding entries (or lack thereof) in the "model registry" (JSON file): 

- It's possible/suggested to link to corresponding _individual line_ of the model registry from each specific table entry re the AI model used for an example. See below.
- The first 2 models distinguished by "Ai93" & "Ai148" have near identical metadata, w/ main distinction being a mouse strain (e.g., "Ai148" refers to [this strain](https://www.jax.org/strain/030328) or similar. Where sensible, may be helpful to briefly comment on this context. 
- Not finding an example that uses the Ai148 model. Should try to figure out its source & useful contexts to at least mention w/ light explanation somewhere in README even if not actively exemplified. 
- The Ophys Training & ABO "big data" example uses a model whose filename starts with "2021_07_31_09_49_38_095550_unet_1024...", i.e., its metadata is currently missing from the model registry. 
- The MRI example uses a model whose filename starts with "2020_08_28_00_25_fmri_", i.e., its metadata is currently missing from the model registry
- Possibly consider distinguishing up-front in the README between "slightly" pre-trained 🤖 & "fully" pre-trained 🤖 🤖 models graphically with a key and/or other brief text context. 

![image](https://github.com/user-attachments/assets/7b8b8f6d-fbf9-423a-b4ab-fc7c2defdb10)

**Comment by vijayiyer05** [comment]
I've run through PR #78 & it strongly addresses this issue.

Given that line 26 of the MRI example names an upstream H5 model file that contains the pretraining data, my suggestion is that's the one named in the registry instead of or in addition to the MAT file. 

I also wonder whether the M file that defines the network should have a more forward location.  

I guess the registry has gotten conceptually more complex now that it's juggling both the earlier and newer import workflows. Perhaps best to get everything moved to newer workflow; and then the registry can be designed/streamlined accordingly. 

Something to chew on in 2025!

**Comment by stevevanhooser** [comment]
> Given that line 26 of the MRI example names an upstream H5 model file that contains the pretraining data, my suggestion is that's the one named in the registry instead of or in addition to the MAT file.
> 
> I also wonder whether the M file that defines the network should have a more forward location.

Yes, here was my thinking there: The M file and the function build the network largely by hand, and serve as an example of how to do that in other situations where it may be necessary. But, if someone wanted to apply that model in a future application, they'd probably just want to load the finished product. Therefore, the finished product is available, ready to load, described in the JSON.
