### ISSUE TITLE
Generalize or remove (currently superfluous) setup functions. 

### ISSUE THREAD

**Issue by vijayiyer05** [MATLAB-Community-Toolboxes-at-INCF/DeepInterpolation-MATLAB#74]
This issue concerns a small detail. Insofar as [MCTs-at-INCF](https://github.com/MATLAB-Community-Toolboxes-at-INCF) is a hub for reference projects, some sweat is due the small stuff. 

At of testing this morning , the `setup` functions, both in the root repository directory & the `+deepinterp` package, appear superfluous. In other words: the per-example OIMO links from the README run through with the initial `setup` calls commented out. 

For reference, below is what I think happened that led to their creation/inclusion. 

I propose two alternatives to the current state:
1. Simply remove them. 
2. If the [toolbox best practices](https://github.com/mathworks/toolboxdesign) (meaning: library code in a nested `toolboxes` folder) is strongly preferred, then one could add/use a **generic** `setupToolbox` function that navigates up from the example folder & back down to toolbox folder and adds all its contents recursively to the path. 

@stevevanhooser, do these choices make sense to you?  If so, which would you choose? 

My suggestion would be option 1. For three reasons. One: it does seem great if WDS had **one** project using/exercising the "full" toolbox standards, but it may be sensible to defer that choice. Two, I generally see value of lean/mean that works! Three: this toolbox was already exploring further uses of OOP, so the use of a `deepinterp` namespace is not a "hack" here. 

Whichever you choose: I've assigned this issue to myself 😊 You could await the PR. 

_What (probably) Happened_ 
IIRC, setup function(s) were added to support Open in MATLAB Online for the example live scripts. Similar to the motif used by another project (EXTRACT) for its tutorials.  There were two forces driving the need for a setup function call: 
1. Projects like EXTRACT whose library code is not fully namespaced need this as library code requires more than just current/single folder on path. But: this does not apply to DeepInterpolation. 
2. MATLAB Online had a behavior where the OIMO button would set current folder to match opened example live script. If th i.e., not the root folder, so that an example wouldn't run

**Comment by stevevanhooser** [comment]
Based on what I see in my classes, I'd say 2. A lot of people have problems with the path well into mid-semester, unfortunately, despite my spending a good deal of time on it. So many people come into college or grad school not understanding files and folders (because everyone uses phones and Cloud computing). I'd say this year about 75% of biology/neuro grad students do not know about folders and files (this knowledge peaked in 2010 and has been dropping since).

I think the _best_ solution is to have Matlab Online run a setup function on install, so that installing on Matlab online is more like installing a Toolbox through the Add-On Explorer. Then one could be sure it was added to the path without user input...

Or it depends on the target audience. If it is experienced programmers, then it doesn't matter much.

**Comment by vijayiyer05** [comment]
Thanks for this perspective @stevevanhooser. Let me propose a generic `setupToolbox` function to Toolbox Best Practices and see how that's received. If something gets accepted there, it could simply be cloned here. Otherwise we can explore general-for-WDS-purposes as a fallback. Stay tuned!

**Comment by vijayiyer05** [comment]
Couple of updates: 

1. I've created an [enhancement issue](https://github.com/mathworks/toolboxdesign/issues/28) out of your suggestion
2. I've requested the INCF make a fork of best practices, so a generic home brew function could be stored there in the meanwhile

**Comment by stevevanhooser** [comment]
This was a good discussion. I think we can close it as an active issue, yes?

I will go ahead and do that but @vijayiyer05 feel free to re-open if that's your preference.
